### ISSUE TITLE
Cannot access localhost:8080

### ISSUE THREAD

**Issue by cmagarap** [lmzach09/Python_ChatBot_Google#4]
`----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43946)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "server.py", line 10, in __init__
    super().__init__(*args, directory=DIRECTORY, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------`

**Comment by horberlan** [comment]
did you use linux or win??

**Comment by cmagarap** [comment]
hello, i used linux

**Comment by Lumko** [comment]
Got the same err, using Linux

**Comment by ushavarshini** [comment]
Same ERROR
